### ISSUE TITLE
Roughly how long does it take to run the benchmarks?

### ISSUE THREAD

**Issue by stokesj0001** [intel/svr-info#14]
I ran 

./svr-info -benchmark all

expecting the benchmark to take a minute or two to run. However close to 5min later the benchmark was still running. Could you add a comment in the Readme or a progress bar indicating the expected running time for the benchmarks?

**Comment by harp-intel** [comment]
Thanks for the suggestion. 

For now, approximations:
cpu - 90s
disk - 30s
turbo - 40s
memory - 120s
frequency - (# of cores per socket  + 10)s

**Comment by harp-intel** [comment]
Benchmark runtime info will be added to the repo's README in the next release.
