### ISSUE TITLE
In VM no core frequency found.

### ISSUE THREAD

**Issue by stokesj0001** [intel/svr-info#15]
Hi, this may be user error or an uncovered edge case but I tried running profiling a VM and no core frequency data was found. Is this expected?

![image](https://github.com/intel/svr-info/assets/97129360/844500d7-04c5-48f0-9014-ee36dc1378f0)

**Comment by harp-intel** [comment]
VM is not propagating the correct CPU family/model/stepping so architecture is unrecognized.
