### ISSUE TITLE
README.md points to incorrect targets.example path

### ISSUE THREAD

**Issue by Feelas** [intel/svr-info#35]
Hello team,
In README.md, _See the included [targets.example](https://github.com/intel/svr-info/blob/main/src/orchestrator/targets.example) file for the required file format._ sentence points to stale 404 link.

targets.example seems to have been moved from **src/orchestrator/targets.example** to **cmd/orchestrator/targets.example**

**Comment by harp-intel** [comment]
Thank you. Will address in next release.
