### ISSUE TITLE
additional network interface configurations

### ISSUE THREAD

**Issue by perfsea** [intel/svr-info#37]
I noticed this tool already aggregates IRQ balance settings. Can it also collect the current coalesce settings?
```bash
ethtool -c eth0
```
should do it. I've found `tx-usec` and congestion control settings are also important for network intensive workloads when cpu bound.

**Comment by harp-intel** [comment]
Recreated the request on the PerfSpect repo: https://github.com/intel/PerfSpect/issues/85.
